# Generated by Django 6.0.6 on 2026-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EVALUATED', 'Evaluated'), ('SHORTLISTED', 'Shortlisted'), (
                'REJECTED', 'Rejected'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('ERROR', 'Error')], default='PENDING', max_length=25),
        ),
    ]
