# Generated by Django 6.0.6 on 2026-07-30 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('cover_banner', models.ImageField(blank=True, null=True, upload_to='company/banners/')),
                ('about', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('why_join_us', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('working_mode', models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite')], max_length=10, null=True)),
                ('working_days', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAIPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ai_screening', models.BooleanField(default=True)),
                ('enable_auto_shortlisting', models.BooleanField(default=False)),
                ('minimum_resume_score', models.IntegerField(default=70)),
                ('minimum_experience_years', models.IntegerField(default=0)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('blacklist_keywords', models.JSONField(blank=True, default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0f172a', max_length=7)),
                ('secondary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GST', 'GST Certificate'), ('PAN', 'PAN'), ('REG', 'Registration Certificate'), ('ISO', 'ISO Certificate'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='company/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_head_office', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='companies.company')),
            ],
        ),
    ]
