# Generated by Django 6.0.6 on 2026-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('match_percentage', models.IntegerField(default=0)),
                ('job_role', models.CharField(
                    default='General Role', max_length=255)),
                ('experience_relevancy', models.IntegerField(default=0)),
                ('owned_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('ai_strategy', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
