# Generated by Django 6.0.6 on 2026-08-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_phone_candidateprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_website',
        ),
    ]
